defaults:
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null  
  run:
    dir: .

# Top-level configuration
mode: train

# Data configuration
data:
  path: /scratch/10114/naveen_raj_manoharan/terramechanics/datasets/training/
  batch_size: 8
  noise_std: 6.7e-4
  input_sequence_length: 6
  num_particle_types: 9
  kinematic_particle_id: 3

# Model configuration
model:
  path: /scratch/10114/naveen_raj_manoharan/terramechanics/models/models_gravity_1/
  file: null
  train_state_file: null

# Output configuration
output:
  path: ../terramechanics/rollouts/
  filename: rollout

# Training configuration
training:
  steps: 3000000
  validation_interval: null
  save_steps: 1000
  resume: False
  gravity: null
  parameters: ["encoder", "processor", "decoder"]
  learning_rate:
    initial: 1e-4
    decay: 0.1
    decay_steps: 5000000
  nmessage_passing_steps: 10

# Hardware configuration
hardware:
  cuda_device_number: null

# Logging configuration
logging:
  tensorboard_dir: /scratch/10114/naveen_raj_manoharan/terramechanics/logs/models_gravity_1

# Rendering configuration
rendering:
  mode: gif
  
  gif:
    step_stride: 3
    vertical_camera_angle: 20
    viewpoint_rotation: 0.3
    change_yz: False

# Reptile Configuration
reptile:
  n_task: 2
  parameters: ["encoder", "processor", "decoder"]
  inner_loop:
    n_examples: 2
    iterations: 1000
  
  outer_loop:
    step_size: 1e-1
    iterations: 50000

# Pretrained-Model configuration
pretrained_model:
  path: ../pretrained_model_1/models/
  file: model-500000.pt
  train_state_file: train_state-500000.pt