defaults:
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null  
  run:
    dir: .

# Top-level configuration
mode: train

# Data configuration
data:
  path: ../../terramechanics/datasets/
  batch_size: 2
  noise_std: 6.7e-4
  input_sequence_length: 6
  num_particle_types: 9
  kinematic_particle_id: 3

# Model configuration
model:
  path: ../../terramechanics/models_2/
  file: null
  train_state_file: null

# Output configuration
output:
  path: ../../terramechanics/rollouts/
  filename: rollout

# Training configuration
training:
  steps: 3000000
  validation_interval: null
  save_steps: 1000
  resume: False
  gravity: [0, -0.0000613125]
  learning_rate:
    initial: 1e-4
    decay: 0.1
    decay_steps: 5000000

# Hardware configuration
hardware:
  cuda_device_number: null

# Logging configuration
logging:
  tensorboard_dir: ../logs/terramechanics/models_2

# Rendering configuration
rendering:
  mode: gif
  
  gif:
    step_stride: 3
    vertical_camera_angle: 20
    viewpoint_rotation: 0.3
    change_yz: False
