version: 2.0
jobs:
  gns:
    docker:
      - image: docker pull ghcr.io/geoelements/gns:config
    steps:
      - checkout
      # GCC
      - run:
          name: Train & Test
          command: |
            TMP_DIR="./gns-sample"
            DATASET_NAME="WaterDropSample"
            git clone https://github.com/geoelements/gns-sample
            mkdir -p ${TMP_DIR}/${DATASET_NAME}/models/
            mkdir -p ${TMP_DIR}/${DATASET_NAME}/rollout/
            DATA_PATH="${TMP_DIR}/${DATASET_NAME}/dataset/"
            MODEL_PATH="${TMP_DIR}/${DATASET_NAME}/models/"
            ROLLOUT_PATH="${TMP_DIR}/${DATASET_NAME}/rollout/"
            pytest test/
            echo "Test paths: ${DATA_PATH} ${MODEL_PATH}"
            ls
            python -m gns.train
            echo "Predict rollout"
            ls ./gns-sample/WaterDropSample/models/
            
      - run: 
          name: Black check 
          command: |
            conda install -c conda-forge black -y
            black --check .

workflows:
    version: 2
    build:
        jobs:
            - gns
