version: 2.0
jobs:
  gns:
    docker:
      - image: ghcr.io/geoelements/gns:config
    steps:
      - checkout
      - run:
          name: Train & Test
          command: |
            git clone https://github.com/geoelements/gns-sample ../gns-sample
            pytest test/
            python -m gns.train
            ls ../gns-sample/WaterDropSample/models/
      

workflows:
    version: 2
    build:
        jobs:
            - gns
