name: GNS Train and Test

on:
  workflow_run:
    workflows: ["Build and Push to GHCR"]
    types:
      - completed
  push:
  pull_request:

jobs:
  gns:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/geoelements/gns:config

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: PyTest
      run: |
        pytest test/

    - name: Black check
      run: |
        black --check .
        
    - name: Train GNS
      if: github.event_name != 'workflow_run'
      run: |
        TMP_DIR="./gns-sample"
        DATASET_NAME="WaterDropSample"
        git clone https://github.com/geoelements/gns-sample
        mkdir -p ${TMP_DIR}/${DATASET_NAME}/models/
        mkdir -p ${TMP_DIR}/${DATASET_NAME}/rollout/
        DATA_PATH="${TMP_DIR}/${DATASET_NAME}/dataset/"
        MODEL_PATH="${TMP_DIR}/${DATASET_NAME}/models/"
        ROLLOUT_PATH="${TMP_DIR}/${DATASET_NAME}/rollout/"
        echo "Test paths: ${DATA_PATH} ${MODEL_PATH}"
        python -m gns.train